### ISSUE TITLE
Impossible de créer des Animations ou Parties de Jdr

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#11]
Dès qu'on clique sur "Créer Entertainement" ou "Créer RPGActivity", on obtient l'erreur suivante : 
![y3mrGTouHJ](https://github.com/Mimble-Mimbus/tm_app_back/assets/80389410/8090f274-c9d6-49d5-a07d-5712c3aee806)

Pour reproduire : se placer sur l'onglet "Animations" ou "Parties de JDR".

**Comment by ln-brie** [comment]
maintenant c'est fait =>CRUD à tester ;)
