### ISSUE TITLE
[RpgZone] Supprimer une RpgZone, liée à une Zone, supprime aussi la zone

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#16]
La suppression de la RpgZone ne devrait pas entrainer la suppression de la zone à laquelle elle est rattachée.

Pour reproduire :
Créer une zone.
Cliquer pour ajouter une RpgZone à la zone.
Créer la RpgZone.
Supprimer la RpgZone.
→ La Zone est aussi supprimée.

**Comment by ln-brie** [comment]
Fix mergé. A tester.
