### ISSUE TITLE
[Partie de Jdr] Edition de partie - Erreur Symfony

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#25]
Reproduction : 
- Avoir créer une partie de jdr
- Accéder à la liste de jdr d'une RPGZone
- Editer une partie de Jdr via le bouton [...]

La page de la partie se charge bien et en dessous, on a l'erreur.

![Screenshot 2024-01-24 at 22-30-00 Modifier RpgActivity](https://github.com/Mimble-Mimbus/tm_app_back/assets/80389410/d2125c93-5c54-4b3d-b9b4-56c9a3180320)

**Comment by ln-brie** [comment]
Je n'arrive pas à reproduire l'erreur
