### ISSUE TITLE
[Partie de Jdr] Retour vers les tables de jdr

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#28]
Reproduction : 
 - Aller dans les tables jdr d'une zone RPG
 - Cliquer sur le nom d'une des tables
 - Cliquer sur "gérer les tables de jdr"

La liste nous renvoie aucun résultat alors que ça devrait nous renvoyer vers la liste précédente.

Il faut peut-être simplement virer ce bouton sinon et compter sur la flèche pour revenir en arrière.

**Comment by ln-brie** [comment]
"Gérer les tables de JDR" renvoie vers la liste des créneaux proposés à la réservation, la liste est vide s'il n'y a pas de créneau associé.
