### ISSUE TITLE
[Partie de jdr] Les descriptions ont des balises "<div>" en trop

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#29]
Reproduction : 
 - Créer une nouvelle partie de jdr, avec une description
 - Revenir sur la liste des parties de jdr
 - Cliquer sur "Afficher le contenu" OU cliquer sur le nom de la partie pour avoir le détail

Des balises `<div>` apparaissent dans la description.

![Q0TVymbb9V](https://github.com/Mimble-Mimbus/tm_app_back/assets/80389410/a1ec4b13-05e5-4762-91fe-f4a9734dbc6f)

**Comment by ln-brie** [comment]
Fixed !
