### ISSUE TITLE
[Jdr - Tables - Réservations] Affichage d'une erreur (non bloquante) quand on édite une réservation

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#38]
Quand on édite une réservation, la page se charge bizarrement (problème de css sur le fond mais les champs sont bien là et répondent correctement) et en dessous se charge une grosse erreur.

Début de l'erreur : 
![KCXgBrV0Cy](https://github.com/Mimble-Mimbus/tm_app_back/assets/80389410/15b5d9c4-7379-4710-8e34-bfb43bb3decf)

**Comment by Elanndelh** [comment]
Reproductible depuis la page des réservations (bouton ...) et depuis la réservation elle-même.

**Comment by ln-brie** [comment]
Je ne reproduis pas cette erreur
