### ISSUE TITLE
[Comptes] Aucune possibilité d'ajouter/supprimer une guilde

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#39]
J'imagine que la fonctionnalité n'est juste pas encore développée. 

Je pense que c'est nécessaire pour pouvoir intervenir dans le cas où il y aurait un soucis pour une personne pour raison X ou Y. Ce n'est cependant pas prioritaire.

**Comment by ln-brie** [comment]
done
