### ISSUE TITLE
Impossible de créer des zones

### ISSUE THREAD

**Issue by Elanndelh** [Mimble-Mimbus/tm_app_back#9]
Quand j'essaye de créer manuellement des zones, j'ai l'erreur suivante :
![QuHiULAHak](https://github.com/Mimble-Mimbus/tm_app_back/assets/80389410/0b7329a7-5b6b-448a-b3aa-c27b6f84614f)

Et ce que je sois en filtre sur une organisation ou non.

Pour reproduire : il suffit de cliquer pour ajouter une zone, remplir tous les champs.
C'est au moment de valider en cliquant sur le bouton "Créer" ou "Créer et ajouter un nouvel élément"

**Comment by Elanndelh** [comment]
Même problème pour les paymentables, guildes, les RPG Zones et les quêtes.

**Comment by ln-brie** [comment]
Fix mergé. A tester
